_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 55
                - 105
            "2":
                - 53
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.0
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
Random_state:
    value: null
activation:
    value: relu
batch_size:
    value: 32
beta:
    value: 0
epochs:
    value: 100
hidden_layer_sizes:
    value:
        - 64
        - 32
input_size:
    value: 15
latent_dim:
    value: 16
learning_rate:
    value: 0.01
loss_function:
    value: mse
optimizer:
    value: sgd
weight_init:
    value: he
